### ISSUE TITLE
can't seem to get plugin working

### ISSUE THREAD

**Issue by expertcoder** [Jimdo/serverless-dotenv#5]
Hi, I followed instructions as suggested.

When I run 

```
export SLS_DEBUG=* ; sls dotenv
```
I see this output (truncated), there appears to be no erorrs

```
...
Serverless: Load command dotenv
Serverless: Invoke dotenv
Serverless: Creating .env file...
```
No `.env` file is generated

##### serverless.yml (truncated)
```
provider:
  name: aws
  runtime: python3.6
  environment:
    MY_VAR: 'myvalue'
...
...
plugins:
  - '@jimdo/serverless-dotenv'

```

serverless version 1.30.3

This plugin seems like a great idea, I want to incorporate this with my automated testing.

Thanks.
